Repository apple/turicreate, pull requests merged in 2018-06, with the labels that each got.

#628 Minor updates to top level readme
  README.md
Labels: docs

#589 Ternary Logic & and | operators
  src/unity/lib/unity_sarray.cpp
  src/unity/lib/unity_sarray_binary_operations.cpp
  src/unity/python/turicreate/test/test_sarray.py
  src/util/bitops.hpp
  test/unity/unity_sarray.cxx
Labels: api-breaking

#776 Removes Fiber
  src/platform/CMakeLists.txt
  src/platform/fiber/CMakeLists.txt
  src/platform/fiber/fiber_barrier.hpp
  src/platform/fiber/fiber_conditional.hpp
  src/platform/fiber/fiber_control.cpp
  src/platform/fiber/fiber_control.hpp
  src/platform/fiber/fiber_group.cpp
  src/platform/fiber/fiber_group.hpp
  src/platform/parallel/execute_task_in_native_thread.cpp
  src/platform/parallel/execute_task_in_native_thread.hpp
  src/platform/parallel/parallel.dox
  src/util/fiber_blocking_queue.hpp
  test/CMakeLists.txt
  test/fiber/CMakeLists.txt
  test/fiber/fiber_test.cpp
  test/fiber/fibo_fiber_test.cpp
  test/parallel/CMakeLists.txt
Labels: cleanup
