Repository apple/turicreate, pull requests merged in 2019-12, with the labels that each got.

#2804 check na data at init_training
  src/python/turicreate/test/test_drawing_classifier.py
  src/toolkits/drawing_classifier/drawing_classifier.cpp
Labels: drawing classifier

#2816 Fixed typo in image augmentation.
  src/ml/neural_net/tf_compute_context.cpp
Labels: p1

#2815 Documentation Updates for 6.0
  LinuxGPU.md
  README.md
Labels: docs
